#!/bin/bash

set -e

target=$HOME/.local/lib/npm/bin/$1
dest=$HOME/.local/bin

if [[ -z $1 ]]; then
    echo "provide executable name"
    exit 1
fi

if [[ ! -f $target ]]; then
    echo "$target does not exist"
    exit 1
fi

if [[ ! -x $target ]]; then
    echo "$target is not executable or user \`$USER\` does not have permission"
    exit 1
fi

ln -sr $target $dest
